


<div class="footer">

<?php echo sprintf($this->translate(' %sZendskeleton modificado por Jaime Mejia%s'), '<span class="zf-green">', '</span>') ?></h1>

<a href="http://frameworkg.com/wiki/index.php?title=Zend_framework">#Zendframework</a>
    <p><a class="btn btn-success btn-lg" href="http://frameworkg.com/wiki/index.php?title=Zend_framework" target="_blank"><?php echo $this->translate('How to work in zendframework2') ?> &raquo;</a></p><h3> hola mundo </h3>